CPP=g++
CFLAGS=-Wall -O1

stringmaster1: stringmaster1.cpp
	$(CPP) -no-pie -fno-stack-protector -o stringmaster1 stringmaster1.cpp $(CFLAGS)
	cp stringmaster1.cpp distrib/stringmaster1.cpp
	cp stringmaster1 distrib/stringmaster1
