CPP=g++
CFLAGS=-Wall -O1

stringmaster2: stringmaster2.cpp
	$(CPP) -o stringmaster2 stringmaster2.cpp $(CFLAGS)
	cp stringmaster2.cpp distrib/stringmaster2.cpp
	cp stringmaster2 distrib/stringmaster2
